# Pyinstagram Exceptions

[_Documentation generated by Documatic_](https://www.documatic.com)

<!---Documatic-section-Codebase Structure-start--->
## Codebase Structure

<!---Documatic-block-system_architecture-start--->
```mermaid
None
```
<!---Documatic-block-system_architecture-end--->

# #
<!---Documatic-section-Codebase Structure-end--->

<!---Documatic-section-pyinstagram.exceptions.NotUpdatedElement-start--->
## [pyinstagram.exceptions.NotUpdatedElement](4-pyinstagram_exceptions.md#pyinstagram.exceptions.NotUpdatedElement)

<!---Documatic-section-NotUpdatedElement-start--->
<!---Documatic-block-pyinstagram.exceptions.NotUpdatedElement-start--->
<details>
	<summary><code>pyinstagram.exceptions.NotUpdatedElement</code> code snippet</summary>

```python
class NotUpdatedElement(InstagramException):

    def __init__(self, element, argument):
        super().__init__("Element '%s' haven't argument %s. Please, update this element" % (element.__repr__(), argument))
```
</details>
<!---Documatic-block-pyinstagram.exceptions.NotUpdatedElement-end--->
<!---Documatic-section-NotUpdatedElement-end--->

# #
<!---Documatic-section-pyinstagram.exceptions.NotUpdatedElement-end--->

<!---Documatic-section-pyinstagram.exceptions.InstagramException-start--->
## [pyinstagram.exceptions.InstagramException](4-pyinstagram_exceptions.md#pyinstagram.exceptions.InstagramException)

<!---Documatic-section-InstagramException-start--->
<!---Documatic-block-pyinstagram.exceptions.InstagramException-start--->
<details>
	<summary><code>pyinstagram.exceptions.InstagramException</code> code snippet</summary>

```python
class InstagramException(Exception):
    pass
```
</details>
<!---Documatic-block-pyinstagram.exceptions.InstagramException-end--->
<!---Documatic-section-InstagramException-end--->

# #
<!---Documatic-section-pyinstagram.exceptions.InstagramException-end--->

<!---Documatic-section-pyinstagram.exceptions.CheckpointException-start--->
## [pyinstagram.exceptions.CheckpointException](4-pyinstagram_exceptions.md#pyinstagram.exceptions.CheckpointException)

<!---Documatic-section-CheckpointException-start--->
<!---Documatic-block-pyinstagram.exceptions.CheckpointException-start--->
<details>
	<summary><code>pyinstagram.exceptions.CheckpointException</code> code snippet</summary>

```python
class CheckpointException(AuthException):

    def __init__(self, username, checkpoint_url, navigation, types):
        super().__init__(username, 'need verification by checkpoint')
        self.checkpoint_url = checkpoint_url
        self.navigation = navigation
        self.types = types
```
</details>
<!---Documatic-block-pyinstagram.exceptions.CheckpointException-end--->
<!---Documatic-section-CheckpointException-end--->

# #
<!---Documatic-section-pyinstagram.exceptions.CheckpointException-end--->

<!---Documatic-section-pyinstagram.exceptions.AuthException-start--->
## [pyinstagram.exceptions.AuthException](4-pyinstagram_exceptions.md#pyinstagram.exceptions.AuthException)

<!---Documatic-section-AuthException-start--->
<!---Documatic-block-pyinstagram.exceptions.AuthException-start--->
<details>
	<summary><code>pyinstagram.exceptions.AuthException</code> code snippet</summary>

```python
class AuthException(InstagramException):

    def __init__(self, username, message=''):
        super().__init__("Cannot auth user with username '%s': %s" % (username, message))
```
</details>
<!---Documatic-block-pyinstagram.exceptions.AuthException-end--->
<!---Documatic-section-AuthException-end--->

# #
<!---Documatic-section-pyinstagram.exceptions.AuthException-end--->

<!---Documatic-section-pyinstagram.exceptions.IncorrectVerificationTypeException-start--->
## [pyinstagram.exceptions.IncorrectVerificationTypeException](4-pyinstagram_exceptions.md#pyinstagram.exceptions.IncorrectVerificationTypeException)

<!---Documatic-section-IncorrectVerificationTypeException-start--->
<!---Documatic-block-pyinstagram.exceptions.IncorrectVerificationTypeException-start--->
<details>
	<summary><code>pyinstagram.exceptions.IncorrectVerificationTypeException</code> code snippet</summary>

```python
class IncorrectVerificationTypeException(AuthException):

    def __init__(self, username, type):
        super().__init__(username, "incorrect verification type '%s'" % type)
        self.type = type
```
</details>
<!---Documatic-block-pyinstagram.exceptions.IncorrectVerificationTypeException-end--->
<!---Documatic-section-IncorrectVerificationTypeException-end--->

# #
<!---Documatic-section-pyinstagram.exceptions.IncorrectVerificationTypeException-end--->

[_Documentation generated by Documatic_](https://www.documatic.com)